name: Phoenix_TestAutomation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "30 18 * * *"
  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        type: choice
        options: [qa, uat, dev]
        default: qa
        required: true
      suite_file:
        description: "TestNG xml Files"
        type: choice
        options: [testng.xml, smoke.xml, regression.xml]
        default: testng.xml
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Creating the .env file
        run: |
              "echo DB_URL=${{ secrets.DB_URL }}" >> .env
              "echo DB_USER=${{ secrets.DB_USER }}" >> .env
              "echo DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: Set default values for inputs
        id: defaults
        run: |
          echo "suite_file=${{ github.event.inputs.suite_file || 'testng.xml' }}" >> $GITHUB_OUTPUT
          echo "env=${{ github.event.inputs.env || 'qa' }}" >> $GITHUB_OUTPUT

      - name: Build with Maven
        run: mvn test -DsuiteXmlFile="${{ steps.defaults.outputs.suite_file }}" -Denv="${{ steps.defaults.outputs.env }}"

      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Surefire Reports
          path: target/surefire-reports
          retention-days: 10
